# Generated by Django 4.2.17 on 2025-09-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Enter A volid title', max_length=30),
        ),
    ]
