# Generated by Django 4.2.17 on 2025-09-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Enter A volid title', max_length=30, unique=True),
        ),
    ]
