# Generated by Django 4.2.17 on 2025-09-02 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 2, 17, 17, 12, 716057, tzinfo=datetime.timezone.utc)),
        ),
    ]
